fix: add verbosity flags to resume command
salesforcecli/plugin-devops-center pull request #146
Opened 2023-04-05 19:55 UTC by EstebanRomero84

### What does this PR do?
Adds verbosity flags to resume command.
### What issues does this PR fix or reference?

[Insert GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NG4OJYA1/view)

### Functionality Before

**sf project deploy pipeline resume** does not have --concise and --verbose flags.

### Functionality After

**sf project deploy pipeline resume** has --concise and --verbose flags.

2023-04-10 19:11 UTC, JuanStenghele-sf requested changes
This looks really good! Just some test suggestions and we should also update the readme.md with the concise and verbose flags info.

2023-04-10 19:11 UTC, JuanStenghele-sf commented on test/commands/project/deploy/pipeline/resume.test.ts
> +      .command(['project deploy pipeline resume', `-i=${mockAorId}`, '--verbose'])
How about a test to check that stubDisplayEndResults is not called when the verbose flag is not used? And another one for the concise case (the output should be the same as if it was not used)?

2023-04-10 20:57 UTC, EstebanRomero84 commented on test/commands/project/deploy/pipeline/resume.test.ts
> +      .command(['project deploy pipeline resume', `-i=${mockAorId}`, '--verbose'])
Good catch. I updated the tests and the READE file.
Thanks.

2023-04-11 20:28 UTC, JuanStenghele-sf approved these changes
Great job!

2023-04-12 13:42 UTC, merged